name: Deploy Nia Rivers Website

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up PHP and cache Composer dependencies
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pdo, pdo_mysql, bcmath, soap
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-progress --no-dev --optimize-autoloader

      # Step 3: Set up Node.js and build frontend assets
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install NPM Dependencies
        run: npm install

      - name: Build Frontend Assets
        run: npm run build

      # Step 4: Deploy built files to the server using SSH
      # We will exclude the .env file and storage directory to avoid overwriting them
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.PROJECT_PATH }}
          EXCLUDE: "/.env, /storage/, /node_modules/, /.git/, /.github/"

      # Step 5: Run post-deployment commands on the server
      - name: Run Post-Deployment Commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            echo "🚀 Running post-deployment commands..."
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan migrate --force
            echo "✅ Deployment complete!"
